from tkinter import *
master = Tk()
Label(master, text='CUSTOMER NAME').grid(row=0)
Label(master, text='CUSTOMER NUMBER').grid(row=1)
Label(master, text='CUSTOMER ADDRESS').grid(row=2)
Label(master, text='PHONE NUMBER').grid(row=3)
e1 = Entry(master) 
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e1.grid(row=0, column=1) 
e2.grid(row=1, column=1)
e3.grid(row=2, column=2)
e4.grid(row=3, column=3)
mainloop()
